### ISSUE TITLE
how do you make ext4 file system?

### ISSUE THREAD

**Issue by shun12a** [nixgnauhcuy/nxp-uuu-qt-tool#1]
I use my own created files to convert to ext4 will have binary errors, how do you generate ext4 files?thaks

**Comment by nixgnauhcuy** [comment]
@shun12a  I utilize Buildroot to construct my root filesystem, and I possess notes documented in Chinese, which might serve as a reference for you. Should you require them, feel free to provide me with your email address.

**Comment by nixgnauhcuy** [comment]
Due to the inactivity of this issue, I will close it. If you have any other feedback, you can reopen it.
